# Generated by Django 3.0.5 on 2020-05-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
