# Generated by Django 3.0.5 on 2020-05-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20200504_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='points',
            new_name='dislikes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='points',
            new_name='dislikes',
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
