# Generated by Django 3.0.5 on 2020-05-05 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0009_auto_20200505_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikers',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likers',
        ),
        migrations.RemoveField(
            model_name='post',
            name='dislikers',
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
